version: '3.8'
services:
  db:
    container_name: database-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    container_name: api-golang
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
