name: CI/CD for Go backend with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19' # Substitua pela versão do Go que você está usando

      # - name: Run tests
      #   run: go test ./...

      - name: Build Docker image
        run: docker build -t rafaeloliverone/golang-api:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push rafaeloliverone/golang-api:latest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy with Docker Compose
        run: docker-compose up -d

      - name: Verify deployment
        run: curl http://localhost:8080/ping # Substitua "your_port" pela porta que seu servidor backend está escutando
